# Generated by Django 4.1.4 on 2022-12-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_user_created_at_remove_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="k", max_length=255),
            preserve_default=False,
        ),
    ]
